### ISSUE TITLE
Multi level embedded document doesn't work

### ISSUE THREAD

**Issue by qpi** [consultnn/yii2-mongodb-embedded#12]
I've tried to add embedded document inside an embedded document and it doesn't work. I receive "Unknown Property" for the attribute:

"Getting unknown property: common\models\embedded\FirstLevelEmbedded::_second_level_embedded"

**Comment by serieznyi** [comment]
@qpi Can you give more info about yours problem? How about body of yours model `FirstLevelEmbedded`

**Comment by serieznyi** [comment]
Close because https://github.com/consultnn/yii2-mongodb-embedded/issues/13#issuecomment-232664691

**Comment by josevavia** [comment]
I want to reopen this issue if is possible. I have the same problem, a here is an example of my code

First, the parent class:

```
class Person extends CActiveRecord
{
	public function attributes()
	{
		return [
			'_id',
			'first_name',
			'last_name',
			'_settings',
		];
	}

	public function behaviors()
	{
		$behaviors = parent::behaviors();
		$behaviors['settings'] = [
			'class' => EmbedsOneBehavior::className(),
			'attribute' => '_settings',
			'embedded' => PersonSettings::className(),
		];

		return $behaviors;
	}
}
```

First subdocument here:

```
class PersonSettings extends EmbeddedDocument
{
	public $bank_info;

	public function attributes()
	{
		return [
			'_bank_info'
		];
	}

	public function behaviors()
	{
		$behaviors = parent::behaviors();
		$behaviors['bank_info'] = [
			'class' => EmbedsOneBehavior::className(),
			'attribute' => '_bank_info',
			'embedded' => PersonBankInfo::className(),
		];

		return $behaviors;
	}

	public function rules()
	{
		return [
				['bank_info', 'safe'],
		];
	}
}
```

```
class PersonBankInfo extends EmbeddedDocument
{
	public $account_number;
	public $iban;

	public function rules()
	{
		return [
			[['account_number', 'iban'], 'safe'],
			['iban', 'app\validators\EIBANValidator'],
		];
	}
}
```

When I try to `validate()` an instance of Person, I get the error:
```
Getting unknown property: app\models\PersonSettings::_bank_info
```

Debugging the code, I found that the problem is here:

```

    public function getStorage()
    {
        if (empty($this->_storage)) {
            $this->_storage = $this->createEmbedded(
                (array)$this->owner->{$this->attribute},
                false,
                ['formName' => $this->setFormName ? Html::getInputName($this->owner, $this->fakeAttribute) : null]
            );
        }
        return $this->_storage;
    }
```

For the first level subdocument (PersonSettings), whe the code executes `$this->owner->{$this->attribute}`, goes to the magic getter of BaseActiveRecord, returning null, but when it executes this line for the second level subdocument (PersonBankInfo), as it does not inherits ActiveRecord, executes the getter of Component, launching the `Getting unknown property` exception.

I hope somebody find this info helpful

**Comment by sokrat** [comment]
Try to rename
```
 public $bank_info;
```
to
```
public $_bank_info;
```
and remove attributes() method

**Comment by josevavia** [comment]
Thanks sokrat, tt works!! 

But now I have one problem: in mongodb, the object in person collection now has an object named `_settings` (with underscore), and this object has another object `_bank_info`, ¿it is normal?

The problem is, when I serialize the object (to use it in REST api), things goes crazy with this result:
```
"settings": {
    "_bank_info": {
        ....
   }
}
```

Also, renaming the property to `_bank_info` prevents me using `$person->settings->bank_info`, I need to use `$person->settings->_bank_info`

Is this extension really tested with nested levels of subdocuments? If not, I am really interested in trying to improve the code to support this.

**Comment by sokrat** [comment]
```$person->settings->bank_info``` should work and contains EmbeddedDocument, ```$person->settings->_bank_info``` contains raw data from database.
```$person->settings->bank_info``` does not work?
