### ISSUE TITLE
Insert more sub document for the same "Embedded Model Class" at the same time

### ISSUE THREAD

**Issue by cicoph** [consultnn/yii2-mongodb-embedded#2]
I have a question. If I need to insert more sub document for the same "Embedded Model Class" at the same time and validate each before update with $addToSet with foreach it is possible to load each embedded model and validate? And if it is possible HOW? This link is the code that for me doesn't works: http://pastebin.com/t8HJGFnW

Thank you

**Comment by sokrat** [comment]
Hi.
$addToSet  is a low level database operation, impossible intercept it in Active Record.
"Embedded Model Class" is a more extensible "Model Class". You can work with it how with simple Model class. 

I dont understand what your code should do. Can you show view and models?

**Comment by cicoph** [comment]
Hi, thank you for reply. These are my Models -> http://pastebin.com/E0BmRwzM , and this is my view _form.php -> http://pastebin.com/ziEckT6S if I try, in the controller, to load $_POST on the embedded model it return false and the model is NULL

**Comment by sokrat** [comment]
If I understand rightly, you want create empty model and init "attivo" attribute three(or more)  embedded models. Right?

Your code does not working because you call load() method of embedded model, but form name is different. You can simply call `$prec->load($test, '')` to load data, and then validate it.

But I think, more simple way add subdocuments directly to the parent model. 
Controller for example:

```
public function actionStep1()
{
    $model = new Bilancio(['scenario' => 'step1']);
    $model->attivo = [[],[],[]]; // or more empty arrays

    if ($model->load(Yii::$app->request->post())) {
        $anno = $model->anno;
        foreach ($model->attivo as $value) {
            $value->anno = $anno;
        }
        if ($model->validate() && $model->save(false)) {
            Yii::$app->session->setFlash('success', 'BACKEND_FLASH_FAIL_ADMIN_CREATE');
            return $this->redirect(['step2', 'id' => (string)$model->_id]);
        } else {
            Yii::$app->session->setFlash('danger', 'BACKEND_FLASH_FAIL_ADMIN_CREATE');
        }
    }
    return $this->render(
        'create',
        [
            'model' => $model,
        ]
    );
}
```

and view:

```
<div class="row">
    <div class="col-md-12">
        <?= $form->field($model, 'anno')->textInput(); ?>
        <?php                 //var_dump($model->attivo);?>
            <?php
            if($model->isNewRecord)
                $valori = $model->attivo;
            else
                $valori = $model->passivo;

            foreach ($valori->current()->safeAttributes() as $name) {
                echo '<div class="row">';
                if($name == 'anno')
                    continue;
                foreach ($valori as $index => $valore) {
                    if ($index == 0) {
                        echo $form->field($valore, $name, ['options' => ['class' => 'col-lg-6']])->textInput();
                    } else {
                        echo $form->field($valore, $name, ['options' => ['class' => 'col-lg-3']])->textInput()->label(false);
                    }
                 }
                echo '</div>';
            }
            ?>
    </div>
</div>
```

It works because when attaching embedded model, her attribute is changing and parent model can load $_POST data for embedded too.

Or if you want add infinity embedded models, you should write javascript plugin like this (http://joxi.ru/VrwWlGKCDGnXrX) and add embedded models dinamicly. First version without readme available (https://github.com/consultnn/yii2-multi-input), later I will add new version with support embedded documents.

**Comment by cicoph** [comment]
Yes, it right, this solution is clean and fast. Thank you for the your new point view. I will try to use your extension yii2-multi-input :)
